services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        USER_ID: "${WWWUSER:-1000}"
        GROUP_ID: "${WWWGROUP:-1000}"
        USER: "${USER:-whoami}"
    container_name: php_app
    image: expense:latest
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "9003:9003"
    volumes:
      - ../src:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - expense-network

  nginx:
    image: nginx:alpine
    container_name: php_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - expense-network

  db:
    image: mysql:8.0
    container_name: php_db
    restart: always
    volumes:
      - "./storage/mysql:/var/lib/mysql"
      - "./mysql/:/etc/mysql/conf.d/"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - expense-network

  pma:
    container_name: php_pma
    image: phpmyadmin:5.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=php_db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=3306
        # depends_on:
        #- hotel.db
    ports:
      - 8888:80
    networks:
      - expense-network

  mailhog:
    container_name: php_mailhog
    image: mailhog/mailhog
    restart: always
    logging:
      driver: none
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - expense-network

  redis:
    image: redis:latest
    container_name: php_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass mypassword
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge
