version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:alpine
    container_name: php_nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d/
